 /* 
  This file is automatically generated. 
*/

namespace MDA;

public abstract class Stmt {
  public interface IVisitor <T> {
    T VisitBlockStmt(Block stmt);
    T VisitExpressionStmt(Expression stmt);
    T VisitPrintStmt(Print stmt);
    T VisitVarStmt(Var stmt);
  }

  public class Block : Stmt {
    public Block(List<Stmt> statements) {
      this.Statements = statements;
    }

     public override T Accept<T>(IVisitor<T> visitor) {
      return visitor.VisitBlockStmt(this);
    }

    public List<Stmt> Statements { get; set; }
  }

  public class Expression : Stmt {
    public Expression(Expr expr) {
      this.Expr = expr;
    }

     public override T Accept<T>(IVisitor<T> visitor) {
      return visitor.VisitExpressionStmt(this);
    }

    public Expr Expr { get; set; }
  }

  public class Print : Stmt {
    public Print(Expr expr) {
      this.Expr = expr;
    }

     public override T Accept<T>(IVisitor<T> visitor) {
      return visitor.VisitPrintStmt(this);
    }

    public Expr Expr { get; set; }
  }

  public class Var : Stmt {
    public Var(Token name, Expr? initializer) {
      this.Name = name;
      this.Initializer = initializer;
    }

     public override T Accept<T>(IVisitor<T> visitor) {
      return visitor.VisitVarStmt(this);
    }

    public Token Name { get; set; }
    public Expr? Initializer { get; set; }
  }


  public abstract T Accept<T>(IVisitor<T> visitor);
}
